---
title: "Final Project"
author: "Shannon Baker"
output: html_document
---

[Final Project R Script](https://github.com/ShannonBa/Data_Course_BAKER/blob/main/Final_Project/Final_Project_script.R)

My final project review how images were created to analyze what genes in mice affect aging and how these genes can be changed to reverse aging in mice. 

[Reprogramming to recover youthful epigenetic information and restore vision](https://rdcu.be/ch1re)

___

[Home](https://shannonba.github.io/index.html) | [About me](https://shannonba.github.io/AboutMe) | [Final Project](https://shannonba.github.io/Final_Project) | [Hobbies](https://shannonba.github.io/Hobbies)

<style>
  body {
    background-color: #FFEABF;
    margin-top: 50px;
  }

 /*Navigation Panel*/
  /*Navigation panel position - ul, li, li a, and .active*/
    ul{
      list-style-type: none;
      margin: 0; /*Top Margine*/
      padding: 0; /*Padding of HOME from the edge*/
      overflow: hidden;
      background-color: #333;
      position: fixed;
      top: 0; /*Does Nothing*/
      width: 100%; /*Does Nothing*/
      }
    ul {
        position: fixed;
        top: 0; /*Does Nothing*/
        width: 85%; /*Adjusts the width of the background on the NAVIGATION BAR.*/
      }
    li {
        float: left;
      }
    li a {
        display: block;
        color: white;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
      }
    li a:hover:not(.active) {
        background-color: #111;
      }
    .active {
        background-color: #F0BB53;
      }
</style>

  <ul>
    <li><a href="index.html">Home</a></li>
    <li><a href="AboutMe.html">About Me</a></li>
    <li><a class="active" href="Final_Project.html">Final Project</a></li>
     <li><a href="Hobbies.html">Hobbies</a></li>
  </ul>